// import { readFileSync } from 'fs';
//

// console.log(readFileSync('./README.md', 'utf-8'));

const productsDataBase = [
  {
    id: '1',
    name: 'You Can Be Anything',
    type: 'Educational Book',
    price: '€',
    image: '/spongebob/1.png',
    width: '550',
    height: '300',
    imageType: '.png',
  },
  {
    id: '2',
    name: 'Drinkable Sausage',
    type: 'Refreshment',
    price: '€',
    image: '/spongebob/2.png',
    width: '500',
    height: '300',
    imageType: '.png',
  },
  {
    id: '3',
    name: 'Gush and Flush',
    type: 'Medicine',
    price: '€',
    image: '/spongebob/3.png',
    width: '550',
    height: '300',
    imageType: '.png',
  },
  {
    id: '4',
    name: 'Midnight Pincer',
    type: 'Perfume',
    price: '€',
    image: '/spongebob/4.png',
    width: '400',
    height: '400',
    imageType: '.png',
  },
  {
    id: '5',
    name: 'Modern Dentistry',
    type: 'Health Magazine',
    price: '€/Month',
    image: '/spongebob/5.png',
    width: '550',
    height: '400',
    imageType: '.png',
  },
  {
    id: '6',
    name: 'Rocky Road',
    type: 'Dessert',
    price: '€',
    image: '/spongebob/6.png',
    width: '500',
    height: '300',
    imageType: '.png',
  },
  {
    id: '7',
    name: 'Long Tan and Handsome',
    type: 'Lifestyle Magazine',
    price: '€/Month',
    image: '/spongebob/7.png',
    width: '550',
    height: '400',
    imageType: '.png',
  },

  {
    id: '8',
    name: 'Canned Bread',
    type: 'Energizer',
    price: '€',
    image: '/spongebob/8.jpg',
    width: '550',
    height: '400',
    imageType: '.jpg',
  },
  {
    id: '9',
    name: 'Fancy Living Digest',
    type: 'Magazine',
    price: '€',
    image: '/spongebob/9.png',
    width: '550',
    height: '400',
    imageType: '.png',
  },
];

export default productsDataBase;
