import Head from 'next/head';
import Layout from '../components/Layout';

export default function About() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Shopping Cart</h1>
      <p>Shopping Cart</p>
    </Layout>
  );
}
