import { css } from '@emotion/react';
import Head from 'next/head';
import Layout from '../components/Layout';

const cartStyle = css`
  margin: auto;
  text-align: center;
  position: relative;
`;
export default function Cart() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div css={cartStyle}>
        <h1>Shopping Cart</h1>
        <p>Shopping Cart</p>
      </div>
    </Layout>
  );
}
