import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/Layout';
import vercelLogo from '../public/vercel.svg';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1>Home page</h1>
      <p>Home page content</p>

      <Image src={vercelLogo} alt="Vercel" />
    </Layout>
  );
}
