import { css } from '@emotion/react';
import Head from 'next/head';
import Image from 'next/image';
import Layout from '../components/Layout';
import BikiniBottom from '../public/Styling/Bikini_Bottom.png';

const homeStyle = css`
  position: absolute;
  text-align: center;
  color: #f7e948;
  -webkit-text-stroke: 1.5px black;
  font-size: 30px;
  margin-left: 650px;
  margin-top: 60px;
  z-index: 1;
  font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
  text-decoration: uppercase;
`;
const backgroundStyling = css`
  z-index: -2;
  margin: -10px;
  margin-top: -100px;
`;
export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div css={homeStyle}>
        <h1></h1>
        <p></p>
      </div>
      <div css={backgroundStyling}>
        <img
          src="/Styling/Bikini_Bottom.png"
          alt="Background Logo Bikini Bottom"
        />
      </div>
    </Layout>
  );
}
